### ISSUE TITLE
Not working with Python 3.8

### ISSUE THREAD

**Issue by batorskik** [MicrosoftDocs/vsts-docs#6339]
I'm getting following error with above steps for Linux ("azure-pipelines-steps-linux.yml"):

AttributeError: module 'time' has no attribute 'clock'

As a workaround I use Python in version '3.7' instead '3.x'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9480b69-ca1f-55bc-8505-49c51d9f205e
* Version Independent ID: 03df29bf-108d-6ffc-bb3e-b29fb8a1e46c
* Content: [Azure DevOps CLI in Azure Pipeline YAML - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops#feedback)
* Content Source: [docs/cli/azure-devops-cli-in-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/azure-devops-cli-in-yaml.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by KathrynEE** [comment]
@geverghe - Can you address this issue?

**Comment by geverghe** [comment]
This is a known issue that we have a dependency on Azure CLI - https://github.com/Azure/azure-cli/pull/10777. Should be fixed once the latest version is available.

**Comment by KathrynEE** [comment]
@batorskik - Thank you for the feedback.  Closing this issue as answered by geverghe.
